import Head from 'next/head'
import {Inter} from '@next/font/google'
import {useEffect, useState} from "react";
import s from '../styles/Home.module.scss'
import {ProductType} from "../components/types";
import ProductLine from "../components/ProductLine";
import CreateForm from "../components/CreateForm";
import Header from "../components/Header";

const inter = Inter({subsets: ['latin']})

// TODO - nice to have: favicon cu logo-ul timberhub
// TODO create type for data

export default function Home() {
    const [data, setData] = useState<ProductType[]>([]);
    const [createFormVisible, setCreateFormVisible] = useState<boolean>(false);

    const getData = () => {
        fetch('data.json'
            , {
                headers: {
                    'Content-Type': 'application/json',
                    'Accept': 'application/json'
                }
            }
        )
            .then(function (response) {
                return response.json();
            })
            .then(function (res) {
                setData(res.rows);
            });
    }

    useEffect(() => {
        getData()
    }, [])

    console.log(data)
    return (
        <div className={s.app}>
            <Head>
                {/*TODO modify head, vezi daca trebuie <NextHead/>*/}
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Header/>
            <div>
                <div className={s.title}>All products</div>
                <input placeholder='Search'/>
                <button type="button" onClick={() => setCreateFormVisible(true)}>+ CREATE PRODUCT</button>
                {data && data.length > 0 && data.map((item: ProductType) => {
                    return <ProductLine product={item} key={item.id}/>
                })
                }
            </div>
            {createFormVisible && <CreateForm/>}
        </div>
    )
}
